### ISSUE TITLE
Support config file

### ISSUE THREAD

**Issue by paour** [letorbi/synoindexwatcher#11]
The script uses hard-coded paths for photos and videos. Would it be possible to add support to override these paths either from a config file or the cmd line?

**Comment by letorbi** [comment]
Hej Paour, thanks for your suggestion. Adding support for a config-file is on top of my todo-list for this project. I'll add this as soon as I find some time for coding.

**Comment by paour** [comment]
This is really neat, thank you for taking the time to add configurability!

**Comment by pmcl77** [comment]
awesome, will have to update again :)

**Comment by pmcl77** [comment]
If I use the rc.d script to start synoindexwatcher, it seems I have to edit the script to add the config file parameter. Should there also be an optional parameter for that script to use the config file?

EDIT: maybe when creating the S99 script, one could pass the config path as well? For now I edited the script manually and it worked fine. :)

**Comment by letorbi** [comment]
@pmcl77 I'm aware of this problem. I'm going to close the init-script issues (#10, #18) today and I will also add a way to add the `--config` argument to the init-script.

I've created a new issue (#24) for further comments and to track the progress.
