### ISSUE TITLE
Help to set inotify limits

### ISSUE THREAD

**Issue by paour** [letorbi/synoindexwatcher#12]
The default limit for inotify watches is absurdly low on Synology. On systems with lots of files and directories in the media folders, this may lead to errors such as `OSError: [Errno 28] No space left on device` when running this script, even when there is still available space.

This page may help with configuring the inotify limit. https://forum.syncthing.net/t/setting-inotify-limit-permanently-on-synology-diskstation/12221

**Comment by letorbi** [comment]
Yeah, the inotify-limits were way too low on my DiskStation as well. I originally planned to add a note on this problem to the readme, but I seem to have forgotten it. However, I will add a section to the readme  ASAP.
