### ISSUE TITLE
Call only synoindex after the system is done writing to a file

### ISSUE THREAD

**Issue by paour** [letorbi/synoindexwatcher#22]
I use rsync to add media to my NAS, and when I turned on detailed logging in this script, I noticed that it was calling synoindex for temporary files created by rsync (they have a random extension). It may be possible to use an extension whitelist #20 to filter these out.

I also had the impression it was calling synoindex when the file is first opened for writing, not just when it is closed after it's done writing. Perhaps introducing a delay between the time inotify notices the change and the time the script calls synoindex, and check if the file still exists at the end of the delay.

**Comment by webcharlyx** [comment]
delaying or even better a trigger only when writing-done would be great:
Monitoring a folder used for PVR(running inside docker container) with synoindexwatcher actually also triggers synoindex on each file blocks write.
I guess IN_CLOSE_WRITE from inotify used by inotify_simple used by inotifyrecursive used by synoindexwatcher might probably be helpfull?

**Comment by letorbi** [comment]
@webcharlyx Yap, I also think that IN_CLOSE_WRITE is the way to go here.

I'm on it and will hopefully push a fix tomorrow.

**Comment by webcharlyx** [comment]
Sorry, to bother again. New files uploaded by filestation _DO_ trigger the `synoindex -a`. But when a file gets created e.g. witch `touch` and then filled with data, they do _NOT_ get indexed. Same file deleted by `rm` trigger `synoindex -d`. Actually I did not test other methods like smb/nfs uploads now.
I encountered the problem because new recordings from TVheadend are no longer indexed now.

**Comment by letorbi** [comment]
Strange - I thought I've tested this scenario. Can you send me the exact commands to re-play the problem? 

EDIT: I see the problem now, too. This is really strange, because my test-script fails even though I know that it worked.

**Comment by letorbi** [comment]
I'm REALLY sorry... I did some last-minute refactoring, which introduced some bugs and I didn't re-test after I was done with the changes. Shouldn't happen, but it did :/

The problems should be fixed with b1b5a6b365315e8df642ee96cb618b8a331afd5b

**Comment by webcharlyx** [comment]
```
admin@diskstation:~$ tail -n2 /var/log/synoindexwatcher.log
2019-11-29 14:38:04,486 INFO Adding watch for path: /volume2/video/Aufzeichnungen
2019-11-29 14:38:04,488 INFO Waiting for media file changes...
admin@diskstation:~$ ls -alh /volume2/video/Aufzeichnungen/test
total 0
drwxrwxrwx+ 1 admin users   0 Nov 29 14:37 .
drwxrwxrwx+ 1 admin users 432 Nov 29 14:37 ..
admin@diskstation:~$ touch /volume2/video/Aufzeichnungen/test/ThisIsATest1.mkv
admin@diskstation:~$ ls -alh /volume2/video/Aufzeichnungen/test/
total 0
drwxrwxrwx+ 1 admin users  32 Nov 29 14:39 .
drwxrwxrwx+ 1 admin users 432 Nov 29 14:37 ..
-rwxrwxrwx+ 1 admin users   0 Nov 29 14:39 ThisIsATest1.mkv
admin@diskstation:~$ tail -n2 /var/log/synoindexwatcher.log
2019-11-29 14:38:04,486 INFO Adding watch for path: /volume2/video/Aufzeichnungen
2019-11-29 14:38:04,488 INFO Waiting for media file changes...
```
and file is also not visible in indexed UPNP-Lib
```

admin@diskstation:~$ rm /volume2/video/Aufzeichnungen/test/ThisIsATest1.mkv
admin@diskstation:~$ tail -n3 /var/log/synoindexwatcher.log
2019-11-29 14:38:04,486 INFO Adding watch for path: /volume2/video/Aufzeichnungen
2019-11-29 14:38:04,488 INFO Waiting for media file changes...
2019-11-29 14:42:26,460 INFO synoindex -d /volume2/video/Aufzeichnungen/test/ThisIsATest1.mkv
```
files created and edited with nano show same:
```
admin@diskstation:~$ nano /volume2/video/Aufzeichnungen/test/ThisIsATest2.mkv
admin@diskstation:~$ tail -n3 /var/log/synoindexwatcher.log
2019-11-29 14:38:04,486 INFO Adding watch for path: /volume2/video/Aufzeichnungen
2019-11-29 14:38:04,488 INFO Waiting for media file changes...
2019-11-29 14:42:26,460 INFO synoindex -d /volume2/video/Aufzeichnungen/test/ThisIsATest1.mkv
admin@diskstation:~$ ls -alh /volume2/video/Aufzeichnungen/test
total 4.0K
drwxrwxrwx+ 1 admin users  32 Nov 29 14:50 .
drwxrwxrwx+ 1 admin users 432 Nov 29 14:37 ..
-rwxrwxrwx+ 1 admin users  14 Nov 29 14:50 ThisIsATest2.mkv
admin@diskstation:~$ rm /volume2/video/Aufzeichnungen/test/ThisIsATest2.mkv
admin@diskstation:~$ tail -n4 /var/log/synoindexwatcher.log
2019-11-29 14:38:04,486 INFO Adding watch for path: /volume2/video/Aufzeichnungen
2019-11-29 14:38:04,488 INFO Waiting for media file changes...
2019-11-29 14:42:26,460 INFO synoindex -d /volume2/video/Aufzeichnungen/test/ThisIsATest1.mkv
2019-11-29 14:55:01,353 INFO synoindex -d /volume2/video/Aufzeichnungen/test/ThisIsATest2.mkv
```

TVheadend is running in docker container, but I don't think this matters.

**Comment by webcharlyx** [comment]
works like a charm, THX!! :+1:
