### ISSUE TITLE
Init generation does not correctly identify python binary

### ISSUE THREAD

**Issue by Giannie** [letorbi/synoindexwatcher#35]
If the script is run with a binary name other than `python`, the init generation does not correctly identify this. In particular, on systems using where `python` is symlinked to `python2` and it is necessary to explicitly call `python3` it would be helpful if the init script would identify this.

Expected behaviour:

`python3 -m synoindexwatcher --generate-init` should create an init file that correctly calls the relevant binary.

**Comment by letorbi** [comment]
Good point and thanks for providing a fix as well 👍 

I've just merged your PR and am closing this issue now.
