### ISSUE TITLE
Whitespace

### ISSUE THREAD

**Issue by thebat98** [letorbi/synoindexwatcher#46]
Thanks for your script !

Unfortunately, I have trouble to use it... and I think this is because of my files : I'm using a lot of white spaces in their names...

I've tried : `synoindex -a /volume1/video/my files/test 1.mkv` which is not working.
Then, `synoindex -a "/volume1/video/my files/test 1.mkv"` which is working... !

How can I fix this issue please ?

Regards,
TheBAT

**Comment by letorbi** [comment]
Hej TheBAT,

you are referring to `synoindex`, but this is the repository of `synoindexwatcher`. Maybe you've posted your issue in the wrong place.

Anyway, I've checked, whether the current version `synoindexwatcher` has problems with white-space-names, but at least my test-cases run fine. Could you provide more information, the output in the console after you have started `synoindexwatcher` for example?

Apart from that I've just fixed another bug, unrelated to your issue. So it might be a good idea to update `synoindexwatcher` before trying again.

Regards,
Torben

**Comment by thebat98** [comment]
Thank you for your reply.
This problem concerns your development, in your script you're using `synoindex`.

Regarding my problem nothing happens : 
![image](https://user-images.githubusercontent.com/798483/103920640-d4b72b80-5111-11eb-8317-ce57481c9bdb.png)

That's why I try manually to use synoindex with args : -d and -a
Then I understand that a pathfile with whitespaces wasn't working.

TheBAT

**Comment by letorbi** [comment]
Thanks for your reply.

Your problem might me be related to the problem I've fixed today. Please upgrade to version 0.11.4 with the command:

```
$ sudo python -m pip install --upgrade synoindexwatcher
```

And start Synoindex Watcher with additional debugging output afterwards:

```
$ python -m synoindexwatcher --loglevel DEBUG
```

The output should give me the information I need to fix the problem.

**Comment by thebat98** [comment]
Your fix did the trick !

Thank you !
