### ISSUE TITLE
Problem on DSM 7.1?

### ISSUE THREAD

**Issue by dooniem** [letorbi/synoindexwatcher#53]
Hi, I believe my indexwatcher stopped working after upgrading from DSM 7.0 to DSM 7.1, does that make sense?
Maybe it's just something silly on my part, could you point me in the right direction here?

```
sudo python -m pip install --upgrade synoindexwatcher
Collecting synoindexwatcher
  Using cached synoindexwatcher-0.11.4-py3-none-any.whl (22 kB)
Requirement already satisfied: inotifyrecursive>=0.3.5 in /usr/lib/python3.8/site-packages (from synoindexwatcher) (0.3.5)
Requirement already satisfied: inotify-simple>=1.3.5 in /usr/lib/python3.8/site-packages (from inotifyrecursive>=0.3.5->synoindexwatcher) (1.3.5)
Installing collected packages: synoindexwatcher
Successfully installed synoindexwatcher-0.11.4

 python -m synoindexwatcher
/bin/python: No module named synoindexwatcher.__main__; 'synoindexwatcher' is a package and cannot be directly executed

```
I'm not well versed in Python on Synology to figure this out by myself :/ 
What am I missing?

**Comment by letorbi** [comment]
Hi, I will investigate the issue once I have some time. Unfortunately I'm quite busy right now...

In the meantime I hope that you can find a solution. Please keep me updated.

**Comment by petermarks** [comment]
I just ran into this too. I followed the installation instructions on a box just upgraded to DSM 7.1 and got the same error message.

I've made some progress using a virtual environment as described in Answer 1 in [this post](https://www.anycodings.com/1questions/2317487/installing-pip-on-a-dsmsynology), but then I get an error when running:

`python -m synoindexwatcher --rebuild-index`

```
Adding files to media-index (this may take some time)...
2022-08-08 16:35:34,761 ERROR An uncaught exception occurred
Traceback (most recent call last):
  File "/volume1/homes/peter/env/lib/python3.8/site-packages/synoindexwatcher/__main__.py", line 218, in <module>
    start()
  File "/volume1/homes/peter/env/lib/python3.8/site-packages/synoindexwatcher/__main__.py", line 177, in start
    add_to_index_recursive(path)
  File "/volume1/homes/peter/env/lib/python3.8/site-packages/synoindexwatcher/__main__.py", line 62, in add_to_index_recursive
    __add_to_index_recursive(path, name)
  File "/volume1/homes/peter/env/lib/python3.8/site-packages/synoindexwatcher/__main__.py", line 48, in __add_to_index_recursive
    if not is_allowed_path(name, -1, is_dir):
NameError: name 'is_allowed_path' is not defined
```

Looking at the code, I can't find `is_allowed_path` defined anywhere and nor can Github. Any suggestions?

**Comment by petermarks** [comment]
I fixed it. It looks like this code path hadn't been tested in a while. Here's the diff of what I did. I don't have time to produce a proper GIT patch at the moment.

[`__main__.py.diff.txt`](https://github.com/letorbi/synoindexwatcher/files/9284342/__main__.py.diff.txt)

... after running this it solved my problem of folders being missed in indexing. Thanks for the script!

**Comment by letorbi** [comment]
Just an update on the original issue: Unfortunately my DSM broke down just right now, when I have some time to spare for the issue :( Anyway, I will look into it, once the defective HDD has been replaced...

**Comment by petermarks** [comment]
In my opinion, using a virtual environment is the way to go as it eliminates the possibility of messing up anything else on the DSM or clashing with any other package or script. Setting up the venv and running the script from the command line was really easy and exactly as described in the link I provided above - actually easier than the original install instructions. However, I guess some more thought is required as to how to run the script on startup and as a different user.

**Comment by letorbi** [comment]
Thanks, for the hint. I will test that installation method once my DSM is working again.

**Comment by dooniem** [comment]
DSM updated. Now I'm back here again, checking if @letorbi has made his DSM work again? *halo smiley*

**Comment by codecivet** [comment]
I had this same issue and was able to resolve it by adding `sudo ` before all the python commands, eg:
```
sudo python -m synoindexwatcher --generate-config | sudo tee /usr/local/etc/synoindexwatcher.conf
```

**Comment by letorbi** [comment]
I have (finally) updated the readme file with installation instructions for DSM 7.x in commit a4d65f9b1fa9beba0dde41e7da4a25ba3550d4e1.

I am closing this issue, but please reopen it, if the instructions are incorrect or unclear.
