### ISSUE TITLE
No space left on device Tips

### ISSUE THREAD

**Issue by LapinFou** [letorbi/synoindexwatcher#57]
First of all, as a Docker user running on DSM7, I want to extend a big thank you for this wonderful Python script.
It truly made my day. 😍

Regarding the potential issue with not enough **inode-watchers**, instead of modifying the `/etc/sysctl.conf` file (which might not survive a DSM update), it could be better to add the following line to the init script (`start_synoindexwatcher` section):
`sysctl -w fs.inotify.max_user_watches=204800`

This should do the job. 👍

I have just one question: since your script is also triggered during SMB/CIFS access, could there be a conflict with the native Synology indexing mechanism?

**Comment by letorbi** [comment]
Nice idea. Kinda obvious, but I hadn't thought about it ;P Fix done with bc73e3a66a87d8f78d32ba7ead82ee845a4d7fea.

PS: Thx for the kind words :)

**Comment by LapinFou** [comment]
Glad you liked the idea. 👌
By the way, you didn't answer my question regarding a possible conflict with the existing Synology indexing mechanism. My guess is that the Syno tool is clever enough to check if the entry already exists before adding a new one.

**Comment by letorbi** [comment]
I have not recognized any conflicts so far. However, I'm quite sure that there are only a few use-cases left where Synoindex Watcher is actually required on a DSM 7 system, because Synology's indexing tool seems to recognize file changes now as well. See [my comment on issue #51](https://github.com/letorbi/synoindexwatcher/issues/51#issuecomment-945678238) and the follow-ups for details.

**Comment by LapinFou** [comment]
I'm using Sonarr (Docker version). When I organize a TV serie (renaming), the Synology's indexing tool definitely doesn't trigger. Thus your script is very useful for this particular case. 👍👍

**Comment by danyfire** [comment]
Same for me I use Sonarr (Docker version) thank you for your tool.
